name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to soerens registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend
          build-args: |
            domain=${{ steps.extract_branch.outputs.branch }}backend.geobingo.io
            VITE_DOMAIN=${{ secrets.VITE_DOMAIN }}
            VITE_GMAPSAPI=${{ secrets.GMAPSAPI }}
            VITE_SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            VITE_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/niggo2k/bingo-frontend-${{ steps.extract_branch.outputs.branch }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/niggo2k/bingo-backend-${{ steps.extract_branch.outputs.branch }}



